flags: {}
packages:
- '.'
- examples/hello-world
- examples/subsites
- examples/blaze-html
- examples/shakespeare
- examples/digestive-functors-hamlet
- examples/rest-json
- examples/streaming-response
- examples/kitchen
- examples/unrouted
- examples/bare-wai
extra-deps:
# Needed for the digestive-functors-hamlet example
- digestive-functors-0.8.3.0
- digestive-functors-blaze-0.6.2.0
- http-types-0.12.1
resolver: lts-11.9
